include:
  - core.apticron
  - core.apt-listchanges
  - core.console
  - core.debconf
  - core.locales
  - core.packages
  - core.profile
  - core.sudo
  - core.timezone
  - core.unattended-upgrades
  - editor
  - util
